### ISSUE TITLE
兼容python版本的命令行

### ISSUE THREAD

**Issue by jtyjty99999** [wangjeaf/ckstyle-node#2]
https://www.npmjs.org/package/commander

https://www.npmjs.org/package/colorful

**Comment by wangjeaf** [comment]
#3 的细化issue

**Comment by wangjeaf** [comment]
ckstyle的命令行，一期先达到如下4个目标哈~
1. `(sudo) npm install -g ckstyle` 一键安装
2. `ckstyle check xxxxxx` 检查
3. `ckstyle fix xxxxxx` 修复
4. `ckstyle compress xxxxxx` 压缩

具体每个命令的参数，请参见 [https://github.com/wangjeaf/CSSCheckStyle#usage](https://github.com/wangjeaf/CSSCheckStyle#usage)

**Comment by wangjeaf** [comment]
颜色高亮，用colors吧： https://www.npmjs.org/package/colors
