### ISSUE TITLE
clean-css 和 ckstyle 压缩对比结果

### ISSUE THREAD

**Issue by youwenda** [wangjeaf/ckstyle-node#27]
发现一个clean-css 和 ckstyle 压缩不同的问题：
1. background 属性

用户自己写的是 background:url(http://a.tbcdn.cn/app/search/search-icons.png) no-repeat scroll -5px -82px transparent; 

ckstyle 保持一致 

clean-css 更大程度压缩  background:url(http://a.tbcdn.cn/app/search/search-icons.png) -5px -82px no-repeat
1. 目前发现color 属性 都变成大写了 不知道这样做目的何在

**Comment by youwenda** [comment]
在进行补充：
1. 用户自己写的 font-family:"tahoma","arial"; 

clean-css 压缩font-family:tahoma,arial; 

ckstyle 压缩font-family: ‘tahoma’, ‘arial’;

**Comment by wangjeaf** [comment]
font-family问题已修复，引号已去除

``` css
font-family: "tahoma", "arial", "Microsoft Yahei";
```

==>

``` css
font-family:tahoma,arial,'Microsoft Yahei'
```

**Comment by wangjeaf** [comment]
颜色值全部大写是规范定的，因为有人大写有人小写，不统一。[规范原文在这里](http://ckstyle.github.io/docs/CSS%20codestyle%20guideline%20from%20RENREN%20FED.pdf)

**Comment by wangjeaf** [comment]
background的压缩，跟 #10 #22 重复，关闭此issue
