### ISSUE TITLE
插件进度表

### ISSUE THREAD

**Issue by jtyjty99999** [wangjeaf/ckstyle-node#5]
插件进度表
- [x] FEDCanNotSetFontFamily  
- [x] FEDCombineInToOne  
- [x] FEDCombineSameRuleSets
- [x] FEDCommentLengthLessThan80
- [x] FEDCss3PropPrefix
- [x] FEDCss3PropSpaces
- [x] FEDDistinguishBrowserExtra
- [x] FEDDistinguishBrowserRule
- [x] FEDDistinguishBrowserRuleSet
- [x] FEDDoNotSetStyleForSimpleSelector
- [x] FEDDoNotSetStyleForTagOnly
- [x] FEDFixCommentInValue
- [x] FEDFixNestedStatement
- [x] FEDFixOutlineZero
- [x] FEDFontSizeShouldBePtOrPx
- [x] FEDHackAttributeInCorrectWay
- [x] FEDHackRuleSetInCorrectWay
- [x] FEDHexColorShouldUpper
- [x] FEDHighPerformanceSelector
- [x] FEDMultiLineBraces
- [x] FEDMultiLineSelectors
- [x] FEDMultiLineSpaces
- [x] FEDMustContainAuthorInfo
- [x] FEDNoAlphaImageLoader
- [x] FEDNoAppearanceNameInSelector
- [x] FEDNoCommentInValues
- [x] FEDNoEmptyRuleSet
- [x] FEDNoExpression
- [x] FEDNoSimpleNumberInSelector
- [x] FEDNoStarInSelector
- [x] FEDNoUnitAfterZero
- [x] FEDNoZeroBeforeDot
- [x] FEDRemoveDuplicatedAttr
- [x] FEDReplaceBorderZeroWithBorderNone
- [x] FEDSelectorNoUnderLine
- [x] FEDSemicolonAfterValue
- [x] FEDShouldNotUseImportant
- [x] FEDSingleLineBraces
- [x] FEDSingleLineSelector
- [x] FEDSingleLineSpaces
- [x] FEDStyleShouldInOrder
- [x] FEDTransChnFontFamilyNameIntoEng
- [x] FEDUnknownCssNameChecker
- [x] FEDUnknownHTMLTagName
- [x] FEDUseLowerCaseProp  
- [x] FEDUseLowerCaseSelector
- [x] FEDUseSingleQuotation
- [x] FEDUseValidValues
- [x] FEDZIndexShouldInRange

**Comment by wangjeaf** [comment]
插件的翻译单独列出来，作为 #3 的一个细化issue

**Comment by jtyjty99999** [comment]
css解析器解析不出 expression
